### PR TITLE
Pr 2 merge (rebase from jekkos/master)

### PR DESCRIPTION
**Pull request by daN4cat**

### CODE REVIEW

**Comment by jekkos** [comment]
Would you mind if I sync this master with the public one? In that case I'll also rebase your mailchimp branch so that new stuff sits on top of latest master commit. This will make things easier to integrate in the end.

**Comment by daN4cat** [comment]
Please keep this master in sync. Don't worry about Mailchimp branch, it's now just for backup. In case we overwrite the master by mistake Mailchimp work is saved :-)

**Comment by jekkos** [comment]
Would you mind if I reduce mailchimp contributions to one commit?

**Comment by jekkos** [comment]
I think this will make changes really clear as it's just one diff for the whole feature

**Comment by jekkos** [comment]
And also easy to rebase on top of public master

**Comment by daN4cat** [comment]
Go ahead, the original is anyway in the branch

**Comment by daN4cat** [comment]
Remember to tag it # 112 and 113

**Comment by daN4cat** [comment]
Mailchimp is now part of the public repo because I preferred to have it part of the mainstream and avoid the constant rebasing.

**Pull request closed without merging**
