### PR TITLE
Rebase from latest jekkos/master

### PR DESCRIPTION
**Pull request by daN4cat**

### CODE REVIEW

**Comment by odiea** [comment]
I am creating a new database to work with.
1. No detailed reports work.
2. Supplier name does not show in items.
3 I created 3 attributes. Only 1 attribute shows on any Category selection.
I guess I need some more info on how this is suppose to work.
4 I created a new item selected a Cat went to update. Error adding updating. I refresh items and the newly created item shows just fine.

**Comment by odiea** [comment]
Just wondering if it would be easier to store the attribute link for items in items? Reinstate the Category column and put the link into there then have it do a lookup or join.

**Comment by daN4cat** [comment]
@jekkos @odiea I force commit to private/master the latest from master and then rebased mailchimp branch and submitted the code to master merging the database upgrade scripts.
It's now cleaner although some duplicate history went in from standard ospos master.

@jekkos you will probably need to rebase your attribute branch with the latest master to remove any conflict due to Steve's work.
Be careful about the fact that I force pushed master so you may want to check again and maybe a rebase would be cleaner.

**Comment by jekkos** [comment]
@daN4cat attributes branch should be in sync again with public and private master repository.

**Comment by jekkos** [comment]
Currently I see what could cause duplicate history now. My private branch contains a rebased version of master. If I merge into master now I guess mailchimp stuff will be duplicated. This is something I'd rather avoid

**Comment by jekkos** [comment]
Unless I force push attributes to master but that is not really recommended practice.. think getting rid of the rebased commits and then merging master is the better solution here

**Comment by jekkos** [comment]
Merging private master into my branch yields duplicate commits as well. Think we should first sync master here with public master and then go from there.

I first synced public master (that wasn't aligned with master here) with my private branch which yields duplicate history now. I might want to revert that in this case

**Comment by daN4cat** [comment]
In my case I went back to the last commit in my private branch and then force commit to my branch. After that I rebased  my branch and then submitted to private and master. So I cleaned things. About what's old it's old. Touching it messes up stuff elsewhere.

**Comment by jekkos** [comment]
MIghtt be a better idea to keep these features rebased with the master of the public repo until we choose to push those changes upstream. Mailchimp stuff will get snowed in now as we have to keep merging upstream into this master which will pollute the history and prevent me from integrating my branche's history in a clean way

**Comment by jekkos** [comment]
Actually the only master branch I'd like to rebase with is public master and not this one

**Comment by jekkos** [comment]
As long as those features are on top of what is public there is no issue. History will be polluted and eventually duplicated otherwise

**Comment by daN4cat** [comment]
Mhhh, not sure I follow.

I considered Mailchimp good enough for the time being so merged into the private master.
Or your preference was to leave it out? I did that to reduce the merging story.

To be honest you can even commit attribute to the private master and we keep going only on master merging the public master when needed. So we reduce the branching as it's an expensive exercise.

**Comment by daN4cat** [comment]
So you can keep going on private master with the attribute only and I focus on consolidating the public master to 3.1.0

**Comment by daN4cat** [comment]
If you keep going with private master you may want to merge the database scripts to the 3.0.2 to 3.1.0 upgrade one. But I leave it to you.

**Comment by odiea** [comment]
Testing the current branch with a new db.
Much improvement in attributes. I think now it will work out well
No receipts work
No Detailed Reports work
Item Kits modal does nothing.
No Items show in Items table.
I will test more after these bugs are fixed.

**Comment by jekkos** [comment]
One more commit for attributes, still some stuff to test  + fix

**Comment by jekkos** [comment]
Thanks for feedback already I need to do a sanity check myself first

**Comment by daN4cat** [comment]
@jekkos any plan to get this work to a conclusion?

**Comment by jekkos** [comment]
actually I'd like to finish for 3.1 but first need to pick up again where I left before new year. Just give it another week so I can try to make some progress.

**Comment by daN4cat** [comment]
Yep no problem, I just wanted to understand where you are. I keep working on public master.

**Comment by jekkos** [comment]
I guess it's mostly stabilizing and regression testing.. a couple of features I'd like to have like date attribute fields aren't yet completely done and I might postpone that til the end

**Comment by jekkos** [comment]
problem for dates is that in the data model currently things are foreseen to store just text.. I might also need to support decimals and datetime in that case

**Comment by daN4cat** [comment]
I would postpone the date time thing to after the rest works through all the layers. Unless you feel it would be too much work to leave it outside on the first pass?

**Comment by jekkos** [comment]
Ok just did a new force push on item attributes most stuff working again still need to do more testing

**Comment by daN4cat** [comment]
I force pushed master-private to be again a mirror of the public master and rebased mailchimp branch and kept it in a separate branch.

I understand the preference is to keep going this way but I assume at certain point we need to agree how to merge everything (if you want to do that?).

Also we need to discuss what we want to do with private / public master copies. 3.1.0 looks mainly driven by the community this time, which is very good and finally what we wanted.
However we need to decide if we add Steve to the private or not as he seems quite active now and willing to move things forward.
Also I see jc, ram and i92 willing to add more, and if we start getting a good group of people to work on larger topics or let say start to assign areas of code then we need to agree if in the end part of the private moves to public.
I'm fine from my side to now push Mailchimp work to public as it might be that other people can add something more. But that would be a personal decision.

With regards to people in the shadow just hoovering code to resell it, well I can see from GA that there is still a number of people that attempt, and some manage to work around the current limits.
But if the community work starts to take off I prefer that common effort to prevail and drop any constraint and worry.
In this way I hope people like jc can feel free to contribute a mobile app to connect to OSPOS instead of mane it a private thing... but we would need to discuss it.

Alternative is to move to private that group but we need to waive copyright restrictions to make sure the contributors are free to reuse for any commercial reason in a mutual exchange way the code.

Thoughts?

**Comment by jekkos** [comment]
I'm quite  happy to see more community involvement lately. This is indeed what I envisioned when I took over the project at the time. 

The option of adding Steve to this repository seems most appealing for now as I'd like to see how things go from here. Other people did have the intention to contribute in the past but without actually bringing anything to the table in the end. So I'm still a bit reluctant there.

If you're fine integrating Mailchimp to public then go ahead I'd say so then we have one thing less to maintain. It would be nice to have the work refined / tested by community as always.

For the attribute story I guess  I need to round up first and will then decide what I do. Maybe we should already go for 3.1 without it as things in public master are more or less stable now and I like the idea of doing smaller feature packed releases more often.

If Steve proves to be contributing more on the longer term then I'd certainly add him to the collaborators list and if he's interested then he can be in this private repository as well.

**Comment by jekkos** [comment]
Once we have more active contributors then I'd also like to consider to move the project to a common organization name on github as it's certainly not only me doing all the work. I think it could also be better for the project's visbiilty in the end.

**Comment by daN4cat** [comment]
It's ok, makes sense.

WRT Mailchimp being made public, I need to think about it a bit more. In the end a lot was done to ramp up the software to a new level so it's time to get something back in exchange of that work.
More contributions later.

**Comment by odiea** [comment]
Getting closer. After the Sale receipts are showing a myriad of php errors. Below is that Item Kits modal now looks like. Still issues with Items not showing Company or Category.
2017-02-22 06_28_31-open source point of sale _ powered by ospos 3 1 0

**Comment by jekkos** [comment]
Ok found that I disabled php errors for some reason, can now reproduce most of these

**Comment by jekkos** [comment]
Ok did another rebase with latest master + fixed bugs regarding receipt completion, item modal error and item row update (category + company_name)

**Comment by jekkos** [comment]
I'll probably be squashing all of this into one commit as well. Makes it easier to rebase with other functionalities

**Comment by odiea** [comment]
Let me know when it is ready to test some more.

**Comment by jekkos** [comment]
Beside the git history I think this is ready to go

**Comment by odiea** [comment]
Items not showing in Items Table. I got the following error after completing a Sale.
2017-02-27 08_08_17-open source point of sale _ powered by ospos 3 1 0
Also the following issue with Attribs Modal.
2017-02-27 08_13_03-open source point of sale _ powered by ospos 3 1 0

**Comment by jekkos** [comment]
Ok Items should show again, also this string is updated, but sale error I can't reproduce. Did you use a specific mode or something? I went to this line in the code but it seems to pass correctly. Or maybe I need to enable display_errors again.

**Comment by odiea** [comment]
After doing 10 more sales that error quit showing.
Returns not working. It displays the pos number select the pos number . Nothing shows in register.
I tried again and the first 4 sales do not return but the 5th sale on returns ok.
Quotes work ok.
Invoice gives the following error.
2017-02-27 14_22_56-mozilla firefox
Attributes language now showing on modal.
Adding new items - hit and miss as far as cat or supplier showing after adding a new item. 
Updating the item works 50% of the time to show cat or supplier.
When that happens I do a refresh and it appears.

**Comment by odiea** [comment]
I got the following error trying to generate barcodes.
2017-02-27 14_49_30-database error

**Comment by odiea** [comment]
2 more issues in Items
2017-02-27 15_00_27-open source point of sale _ powered by ospos 3 1 0
2017-02-27 15_00_46-open source point of sale _ powered by ospos 3 1 0

**Comment by jekkos** [comment]
OK thanks for testing, needs some more review for sure

**Comment by daN4cat** [comment]
@jekkos any plan to get to an end or are you waiting for Steve to submit the tax rework before resuming this?

**Comment by jekkos** [comment]
Not really waiting for him to finish in any way. I stopped progressing on this one but was about to have another look now. Actually I'd like to add it to a separate release, otherwise scope for 3.1 will be too big.

**Comment by daN4cat** [comment]
Yes, separate release it's fine.

I'm just waiting for this tax module rework as we will need to test it a bit and then release 3.1.0 with probably some other bug fix and similar stuff.

**Comment by jekkos** [comment]
Ok did a couple of extra fixes

* inventory + stock modals should be fine
* item kits modal $print_option error was fixed
* invoice template got fixed
* sale return should work ok
* might still be some issues with selecting categories in items (need to look into that)

**Comment by daN4cat** [comment]
@jekkos OK, cool. I'll try to test since @odiea is enjoying his life in a sunny location.

Did you publish the branch in public on purpose? It's now a branch to your public repository.

**Comment by daN4cat** [comment]
Also I'm not sure whether you rebased with the latest master or not. But I'll check the branching this evening.

**Comment by jekkos** [comment]
Ok I did not mean to publish it in public yet. We'll set something up for a next release (at least that's my idea).

Currently known bugs to me are

* Category field might not be reselected correctly after reopening the modal. Although it seems to be saved in db correctly.
* Changing a parent attribute's type might cause some issues with items.. Need to think how to handle this kind of situation

**Comment by jekkos** [comment]
Ok rebase is done with latest public master. Seems to init the db well. Haven't really tested further

**Comment by jekkos** [comment]
Most of functionality seemed ok although it needs more testing.

**Comment by jekkos** [comment]
Did another push of rebase with latest master. All seems to work fine

**Comment by odiea** [comment]
Your not out of the woods yet. More issues are showing. After adding a Category in new Item the Cat does not show in the Items list until it is updated. Have you done any new db changes?
This is a Sale.
2017-04-06 13_08_17-open source point of sale _ powered by ospos 3 1 0
This is the Receipt for the Sale.

This is Takings.
2017-04-06 13_03_52-open source point of sale _ powered by ospos 3 1 0

**Comment by daN4cat** [comment]
I guess attribute branch needs a rebase with the latest changes from Steve.

**Comment by daN4cat** [comment]
@jekkos do you plan to rebase your branch at certain point in time? When Steve has finished with the last part of his rework of the tax story it would be good if you could.
Once done I will try to find some time as I really need to give a last push to this to finally switch my wife's shop to the new version. Almost two years that I work on this and I made no upgrade to her system!!!

**Comment by jekkos** [comment]
Haha same story here man. actually I squashed maybe that last bug this week it's still on my local. The branch should be more or less uptodate

**Comment by jekkos** [comment]
Just takes too much time the way we develop in this application, especially for bigger changes. The technologies and state of codebase are a bit counter productive I'm afraid, no tests, lot's of js fiddling..

**Comment by jekkos** [comment]
But glad to see that more people pick it up since 3.0. That upgrade was really needed to push it forward. Huge time investment I think.

**Comment by daN4cat** [comment]
Not sure we will ever have the time to do a proper redesign and refactoring.
One day I will do some domain modelling and draw a relationship diagram showing better how we should reshape this architecture.
I sketched ideas here and there but I would need to put those on a paper / diagram.

I believe we are nor better nor worse than many other legacy systems outside in this world anyway.

**Comment by jekkos** [comment]
Yes sure it's great to have at least a concrete idea or migration path that would lead to improving the whole thing. After all it's still cool to see that it works for a lot of businesses out there, aside from the technical perspective here.

**Comment by jekkos** [comment]
@daN4cat Ok squashed another couple of bugs + rebased on top of latest master.. afaik no more known issues but need to do some more testing to make sure

**Comment by odiea** [comment]
Once you get this resolved I think it's pretty close.
This is the Table view of Items after adding a new Item.
2017-04-30 11_59_01-open source point of sale _ powered by ospos 3 1 0
Here is the update view after adding the new Item
2017-04-30 11_59_19-open source point of sale _ powered by ospos 3 1 0

**Comment by jekkos** [comment]
@odiea I'll need to test item creation again then. I guess? The category isn't saved after creation, is that what you mean?

**Comment by odiea** [comment]
The add new Item does not save the Category. It must be updated to save and then be shown in Items table view and then it works.

**Comment by jekkos** [comment]
Ok category is saved now on item create. Also rebased with latest master

**Comment by odiea** [comment]
Got that fixed.
I get the following error when going into Store config.
When extracting the zip it says license already there do u want to replace it.
A PHP Error was encountered
Severity: Warning
Message: Invalid argument supplied for foreach()
Filename: controllers/Config.php
Line Number: 138
Backtrace:
File: C:\xampp\htdocs\attribs\application\controllers\Config.php
Line: 138
Function: _error_handler
File: C:\xampp\htdocs\attribs\application\controllers\Config.php
Line: 213
Function: _licenses
File: C:\xampp\htdocs\attribs\public\index.php
Line: 315
Function: require_once

Here is Takings
2017-08-03 13_03_52-open source point of sale _ powered by ospos 3 1 0
 Here is the receipt for that sale.
2017-08-03 13_04_10-open source point of sale _ powered by ospos 3 1 0
This only shows up when I use the 1st newly created Item???

**Comment by odiea** [comment]
It also will not allow to Delete a Sale.

**Comment by jekkos** [comment]
Deleting sales should be retested in master don't even know if it will work there, maybe try to add some customer reward points first..

**Comment by jekkos** [comment]
So you don't see any attributes for other items beside the first one? Did you configure the other attributes to show up in sales?

**Comment by daN4cat** [comment]
I rebased the branch with the latest master and committed.

**Comment by jekkos** [comment]
ah I did the same!

**Comment by daN4cat** [comment]
Today I took again the current OSPOS 1.1 database, upgraded to 3.1.0 (all went fairly well outside few tweaks) moving the item fields I added to 3 custom ones.

Then I attempted to migrate the whole newly created database to this attribute version and things "exploded". Attribute list became a 2GB table!!! I noticed that the list of attributes just for the category exploded in tons of the same value, e.g. TOP, attribute CATEGORY. Many of the same.

Something is not right in this migration. I will now restart removing those 3 custom fields and see what happens.

My database is about 18k rows for Items and about 21k rows for Sales.

Attribute definition is matching the Items rows, but I'm not sure why the links one exploded to more than 10Mil rows.

@jekkos any thoughts?

**Comment by odiea** [comment]
Yes. I ran into that issue too and that is why I started just using a new db instead of updating an old db. At the time it appeared there were a lot of issues so I was hoping once it started working that the problem would go away.

**Comment by daN4cat** [comment]
ok, the problem with the exploded list of categories is something I fixed.

In the script it's missing `DISTINCT`:

> INSERT INTO `ospos_attribute_definitions` (definition_name, definition_type) SELECT DISTINCT category, 'CATEGORY' from ospos_items;

**Comment by daN4cat** [comment]
Now let me check the rest...

**Comment by daN4cat** [comment]
ok, I fixed the table size issue. It was a lack of DISTINCT and therefore the combinatory number was massive.

Anyway I would suggest to customise the script to the number of effectively used custom fields just to avoid empty entries and long delays.

BTW, to create the links even if the number of combinations is reduced it will take some time.
For my case about 18k items it took 200 seconds per custom field.

**Comment by daN4cat** [comment]
BTW, now I have another issue: when I edit an item to check the attributes, the attributes appear and quickly disappear. Weird...

**Comment by odiea** [comment]
Yes and when you perform a Sale and you sell 1 item the receipt may show 2 items sold. This has happened to me 3 or 4 times. Takings shows the correct Sale amount until you print the receipt.

**Comment by odiea** [comment]
And after you enter a new item You have to go back and edit the item to get the other attributes to show on a Sale or receipt.

**Comment by odiea** [comment]
Here is how the sale shows in reports and takings.
2017-09-02 15_20_31-open source point of sale _ powered by ospos 3 1 0

This is what the receipt shows.
2017-09-02 15_20_57-open source point of sale _ powered by ospos 3 1 0

**Comment by daN4cat** [comment]
@odiea but what happens when you try to edit an item, do you see the list of attributes under category or do they disappear as soon as you open the modal dialog box?

**Comment by daN4cat** [comment]
Also I noticed that when you submit the line in the Items table is not refreshed.

**Comment by odiea** [comment]
Here is what I have for a test setup.
2017-09-02 15_58_41-open source point of sale _ powered by ospos 3 1 0

 This is what I see when I edit an Item.
And yes subcategories do show under the category and then disappear.
Category
Subcategory
subcatagory

The after a split second
Category
Subcategory.

**Comment by daN4cat** [comment]
OK, many different things still not fine.

I needed to go squash all the commit to one and tidy up a lot of mistakes that were introduced in the language files. So all of that is fine and build on top of 3.1.0.

About the rest let see if @jekkos finds the time to help and one step at time we will fix and get it done.
This is my next thing.

However I still don't get the category and subcategory thingy. I need to play a bit with that to understand it more.

**Comment by daN4cat** [comment]
Hmmm I'm not sure I follow how this has been designed.

Is the intention to have one category and multiple attributes under?
And can you have different categories?

This two tier hierarchy is not matching what I had as it was a flat story of attributes.

For instance I don't want to have a season attribute for each let say shoes or dress category. The same for colour. Exception could be size as that differs but shirt, blouse, t-shirt have XS, S, M, L and XL. So again you can reuse here sizes across different categories.

Unless you mean to have let say womenswear, footwear, accessory, homeware categories and then attributes for each?

I'll give a try to that approach, but then the upgrade script cannot be generic and everybody will need to rework it according to their taxonomy.

**Comment by daN4cat** [comment]
I was just looking at one example here: https://www.johnlewis.com/ (just because it's a known name in the UK that I picked it up).

There are three levels:
1. home, garden, women, men, child, beauty, sport, etc.
2. under women you have clothing, shoes, accessories, etc.
3. under women/clothing you have shirts, dresses, trousers, etc.

**Comment by daN4cat** [comment]
Testing I can see that a category can become a subcategory. So it's recursive.

**Comment by daN4cat** [comment]
But then the update item modal doesn't allow you to select a subcategory after having selected the category.
I created Clothing and I wanted to select Top. It's not possible.

**Comment by odiea** [comment]
I have not had that much time to devote to this feature because of the issues I was getting. I think it's going to be one of the things we need to play around with before it's released.

**Comment by daN4cat** [comment]
With regards to hierarchy of products, @odiea, what's your current situation?
How do you classify all the items?

**Comment by odiea** [comment]
For me it's not relevant any longer. We closed the thrift store 2 yrs ago. I am just trying to remember how it was done back then.

**Comment by odiea** [comment]
Here are 2 more issues .
The attributes cannot be deleted and when you have a space in the name you get the following.
2017-09-03 07_44_20-open source point of sale _ powered by ospos 3 1 0

**Comment by daN4cat** [comment]
@odiea oh well, I was under the impression you still had that store. So where do you use OSPOS (or plan to use)?

**Comment by odiea** [comment]
OSPOS was never robust enough to use at the old thrift store. I am doing this because I enjoy it and I believe an old dog can learn new tricks.

**Comment by daN4cat** [comment]
@odiea oh good, well many thanks for all the time you spend on this helping us. It looks like none of the three of us managed to really use this version 3.x. I don't think @jekkos ever migrated to it as me.
Such a bunch of funny guys... 2 years of work for fun in the end hahahaha

**Comment by jekkos** [comment]
Yah that's sort of funny. I do still plan to do the move this year tho.. anyway it's nice to learn new things in the end

**Comment by jekkos** [comment]
Think the idea was to either use category with subcategories or a flat hierarchy. Won't have a lot of time this week as some other work has priority at this moment.. 

First have 3.1.1 stable and then I'll rebase and check again.

**Comment by odiea** [comment]
It would be nice to assign basic attributes to Categories. Such as Color,Condition,Size and so on so the attributes do not have to be duplicated for different Categories. What do you think?

**Comment by jekkos** [comment]
So that mean we can have multiple parents for one subcategory?

**Comment by daN4cat** [comment]
Let's step back here.... what's a category and what's an attribute?
To me Category is an item grouping concept, Attribute is a means to describe more the item.
The two should be separate as item aggregates attributes, item belongs to categories.

I would make possible to have group of attributes to be associated to items for convenience, but that grouping of items is not a category.

**Comment by odiea** [comment]
I guess my question would be lists of attributes that would be shown on the items screen along with the Category and Subcategory. A set would include sizes another set would include color another set would include other various descriptions of Items like new or used?

**Comment by odiea** [comment]
Currently the misc list of attributes do not show on the screen unless it is associated with a Category.

**Comment by daN4cat** [comment]
That's my point. We are mixing up group of attributes with categories, a taxonomy concept.

**Comment by odiea** [comment]
A subcategory of Power Tools I have listed as Electric Drill but it shows on the dropdown as Electric%20Drill. Any idea?

**Comment by jekkos** [comment]
seems like an encoding issue.. values are added through ajax to the strings might need to be decoded before they are inserted

**Comment by daN4cat** [comment]
@jekkos are you able to progress this work? I tried looking into the item form js to understand how that works but got a bit lost. However last week end I moved upstream as much as possible of what was not strictly attributes to simplify the rebase story.
Now it's easier to see only the changes that are required.
Also I fixed the new item creation bug on form open, but I need to fix the bug on saving as it throws an error.

**Comment by jekkos** [comment]
I planned to look at it yesterday but got lost fighting weblate issues (database got corrupted there). Changing translations does seem to work now (and emailing as well) but still I don't see those changes reflected to the git repo. Still investigating that and then afterwards I'll try to progress this story.

However at the time I decided to skip the flat attribute addition linkage simply because this UI work requires a lot of jQuery JS to be written which is hard to debug and tedious to write. Also the way attributes are linked to categories now more or less reflects the custom work I did a long time ago on the old version I planned to migrate (after 2 years). In other words I just planned to do a minimal version for my migration needs which could then be extended afterwards.

Looking at it now does give some new idea on how to tackle this, I would just add a dropdown to the label side allowing a user to link attribute definitions to an item. Once selected, a dropdown, text input  or date picker can appear to the right of it, depending on the attribute type we're dealing with. The main difficulty is that for new items you need to 'accumulate' these changes as they can't be saved using ajax because the item itself is not in the database yet. This is something I didn't think about when designing the code for saving selected attributes linked to a category, which lead to the fact that it's probably too complex and hard to understand now.

**Comment by daN4cat** [comment]
I'm a bit wary about this story:

* on one hand I spent 2 years to work on this and still not deployed just because I need 3 attributes (a quick addition on a custom branch scrapping the custom fields will do for me as it is done at the moment)
* on the other hand I would like to do the proper job and see it part of the streamline OSPOS (but this will take who knows how long and depend on your willingness to make the change fully open).

Overall I start being a bit burnt out and I would like a break outside just doing some bug fixing, merge work and release.
I struggle to see me taking a new big feature now to do more work, it's really time consuming and eating time from my private life.
I might work on Reportico a bit to get it right and then see how it can be integrated to OSPOS, but taking time.

So, I might opt to go for the custom work and upgrade from that one unless we can really crack on with this in the short term and close it in a basic form and make it public so other people can help and evolve.

**Comment by jekkos** [comment]
@daN4cat can we add @SteveIreland to the conversation here? He might have some time to finish this off, as I guess I'm in a bit of the same situation as you here.

**Comment by jekkos** [comment]
@daN4cat so you also suggest to keep the category field, and beside that allow recursive use of the attributes (as is only possible now).

This might indeed be a cleaner separation, however, it will take some time to clean that up in the code, as I removed the concept.

**Comment by daN4cat** [comment]
Invited @SteveIreland

**Comment by daN4cat** [comment]
@SteveIreland you should post here not the other side.
Keep the forks separated. Master is up to the latest, the branch with #68 work is attributes one. I keep master up to date and I rebased attributes branch to the latest.
Don't worry about other branches.

**Comment by SteveIreland** [comment]
Sorry I couldn't contribute more this weekend.  I"m going to restart from scratch this week and attempt again to see if I am able to contribute.  I simply couldn't get past that odd "unstaged" changes error.

Thanks.

**Comment by daN4cat** [comment]
No worries, no need to rush

**Comment by jekkos** [comment]
If someone has this branch rebased  with latest master, let me know, otherwise I'll give this a go somewhere this week

**Comment by daN4cat** [comment]
Let me rebase it with the latest before you restart.

**Comment by daN4cat** [comment]
I rebased the branch to the latest master (public and private master are now the same).
I also updated the date of the migration script to be on top of the latest 3.2.0. As you move along you will need to update the date to make sure applies on top of the latest, if that's required. It might not.

**Comment by jekkos** [comment]
I close this one now as it has become too  long..

**Pull request merged**
