### PR TITLE
Rebase with 2.3.3

### PR DESCRIPTION
**Pull request by daN4cat**
Rebase my master with 2.3.3 version

### CODE REVIEW

**Comment by jekkos** [comment]
And your github username/password doesn't work here?

**Comment by odiea** [comment]
I will try my password and see what happens

**Comment by odiea** [comment]
I guess I was not paying much attention. Yes my user name and password work just fine. Thanks

**Comment by odiea** [comment]
I am trying to create a new category.
Attribute Name  clothing.
Attribute type Category.
Nothing in category drop down
Visibility I selected all 
submit
How do I populate the Category drop down.?
I go to items.
The category defaults to nothing
I select clothing
It does not update the table

**Comment by jekkos** [comment]
If you reopen the dialog.. does it show the selected category? There was a refresh issue on the table earlier today that did not show the selected category but in the table only.

**Comment by odiea** [comment]
Currently no categories are showing in items. If I select the Categories 
for more than 1 item the categories disappear. The attribute does show 
in register and receivings but not in items.

**Comment by odiea** [comment]
In attribute definitions as long as the definition_fk shows null it will appear in the category selection drop down.

**Comment by jekkos** [comment]
Correct. Currently subcategories are not supported .. just linking attributes to categories is.

You're right on the categories not showing in items listing. I made that code and think it is still on my other laptop. 

Also you say bulk edit does not work for categories.. that is correct I forgot that one.

**Comment by jekkos** [comment]
What also is important is when attribute value changes it should not impact sales or receivings in the past. Their attributes are frozen so to speak

**Comment by jekkos** [comment]
What about item search and import? Also I need to check reports which might need some queries to be altered

**Comment by odiea** [comment]
Items
Category does not sort.
item update - Company name does not update.
New Item does not retain category you have to update and redo the category.Company name does not update.
Detailed Reports do not work.
Search appears to be working.
Issues
I did an Update that worked.
The Category and Attributes tables are filled with multiple Categories with the same name. Is there going to be a way to just show 1 original category?
After using a Category most of the time the name disappears from the drop down list.
2016-12-29 05_37_33-untitled - notepad

**Comment by daN4cat** [comment]
I close this, we keep the discussion going in #2

**Pull request merged**
