### PR TITLE
Boostrap UI upgrade from cpl2015

### PR DESCRIPTION
**Pull request by daN4cat**
Take the latest from cpl2015

### CODE REVIEW

**Comment by jekkos** [comment]
OK a lot of work going on in some of these branches.

**Comment by jekkos** [comment]
This is nice in a way as we can choose what to integrate where, hoping that there's not too much overlap in code

**Comment by daN4cat** [comment]
Yep, some work. I started with importing that library in GitHub: https://github.com/daN4cat/codeigniter-reportico

I made it to use composer but it's WIP, but before my step with composer I needed to sort out Reportico to use composer.

You start with one and then you get another one and another one...

**Comment by jekkos** [comment]
Do  you think that making some kind of generic reporting functionality inside of ospos would be easy? I haven't worked with it so no idea how easy it is to integrate. But would be awesome if users can configure aggregate / drilldown ... sort of things themselves

**Comment by daN4cat** [comment]
Yes that's the idea. Reportico would allow people to create their own report and save it in XML.

**Comment by daN4cat** [comment]
The challenge would be to embed it with a seamless experience between OSPOS and Reportico.

**Comment by daN4cat** [comment]
I close this because it's part of https://github.com/jekkos/opensourcepos/issues/1433 so no reason to keep it here.

**Pull request merged**
