### PR TITLE
Nerv55 patch 1

### PR DESCRIPTION
**Pull request by nerv55**
Update RU translate

### CODE REVIEW

**Comment by daN4cat** [comment]
@nerv55 many thanks for your help and contribution but actually this fork is just a mirroring of https://github.com/opensourcepos/opensourcepos providing the full installation in case somebody wants it instead downloading from bintray.

Translations are managed using Weblate here: http://translate.opensourcepos.org/
Please go to that tool and contribute your Russian translations so other people can see and review.

Thanks again for the help.

**Comment by nerv55** [comment]
Ok, I will see the tool you suggest.

**Comment by daN4cat** [comment]
Good. I close these pull requests then.

**Pull request closed without merging**
