### PR TITLE
Versão atual

### PR DESCRIPTION
**Pull request by arteiro**

### CODE REVIEW

**Comment by daN4cat** [comment]
Not required anymore.

**Comment by jekkos** [comment]
Always nice to have  the choice  on how to use these kind of solutions, unlike MailChimp which probably claims the right to do what they want with the data you send them.

**Comment by daN4cat** [comment]
Yes, but Mautic is more than Mailchimp and it's free. You can build a campaign concept, send something then automate actions in a tree according to the follow up on what was sent or pushed.
It would be even interesting to understand if something can be automated checking what your customers like or not on social media and target them with some sort of promotion.
Let say they liked a pair of Nike shoes you stock, you could send an email with a 5% discount for Nike shoes at your store over the weekend to only that person.

That's what is the marketing campaign automation about.
When I find the time I want to understand more this tool.

**Comment by daN4cat** [comment]
@jekkos have you heard of a company named Sentiance? It's based in Anvers and they deal with stuff that you may have good skills for. Check www.sentiance.com and they are looking for people.

**Comment by jekkos** [comment]
HI yes I do know them, have been following what they do for some time. Currently working as freelance for another company in Antwerp called REstore. Quite an interesting business they have selling flexible energy to the markets.

**Comment by daN4cat** [comment]
No plans to work on this, so I close.

**Pull request closed without merging**
