### PR TITLE
Nerv55 patch 4

### PR DESCRIPTION
**Pull request by nerv55**
Update RU translate

### CODE REVIEW

**Comment by daN4cat** [comment]
So the mathematical formula is:
  - cash = cash close - cash open - movement from/to safe;
  - total = cash + card + check.

To balance with:
  - cash = cash transactions - due transactions - expenses
  - card = card transactions
  - check = check transactions
  - total = cash + card + check

I always assumed that due was a cash story. Sounds right?

**Comment by odiea** [comment]
Yes. I believe due is a payment that was received that business day.

**Comment by daN4cat** [comment]
Due is a credit, so actually no cash came in... but the problem is when they pick up the old transaction and they permute due to cash, real cash moves in. So that is an issue.

I'm not sure I want to fix this as we don't use the due (credit). I will ignore...

**Comment by odiea** [comment]
I would do that unless Due amount is changed to a minus amount or a balance due.

**Comment by daN4cat** [comment]
@odiea I committed to the branch more changes:
- Fixed the employees part
- Added cash transfer
- Part fixed the sum (it works only with positive numbers). I need to switch to the accounting.js lib to do the correct thing here

Please be aware that you need to change the db table.

**Comment by odiea** [comment]
So far so good.
The following db info needs to be changed to.
ALTER TABLE `ospos_cash_up`
  ADD PRIMARY KEY (`cashup_id`),
  ADD KEY `open_employee_id` (`open_employee_id`),
  ADD KEY `close_employee_id` (close_employee_id`);

**Comment by odiea** [comment]
The way it is now. At close time the employee needs to deduct the opening cash from the till. Then adds up the rest of the cash in the till?

**Comment by daN4cat** [comment]
Thanks I'll fix the indexes.

Not sure I follow. We discussed the maths yesterday. I'll read and think about again later...

**Comment by jekkos** [comment]
@daN4cat Adding business logic in a frontend is never a good idea.

Wouldn't it be better to add a ajax call for that and process the summation in php with the configured locale settings for the store? That will also relieve us from adding an extra javascript plugin just to do a simple summation.
Also it will ease the locale parsing as now you're redoing that logic in jQuery

**Comment by daN4cat** [comment]
@jekkos yes and no, depends on the latency because I wanted to have something more interactive.
But you have a point due to the fact that we already use the backend approach in other places, so let's be consistent.
I will use ajax calls to do that and make the change only when somebody has filled in the field not on keyup.

Better to suggest @objecttothis to do the same for his validation work on giftcards.

**Comment by jekkos** [comment]
Ok understand about the interactivity, there might be a little more latency but I don't think it's worth the pain if you consider all the logic to be done concerning rounding, formatting that's in the backend only..

Maybe I missed @objecttothis his contribution on that part, so might want to give it a look. Always good to better to have validations both on front- and backends.

**Comment by daN4cat** [comment]
@jekkos see #1694. To be honest I didn't look into it too much and thinking on twice he's probably doing something similar on the front end.

**Comment by jekkos** [comment]
Ok good thanks for the pointer. Added same comments there

**Comment by daN4cat** [comment]
BTW, I've added @objecttothis to this repo. It made sense to me as we keep new features in embryonic state here and we might publish them or not.
Also I keep my boutique personal branch here which is visible to you guys but really customise for my needs.

**Comment by jekkos** [comment]
@daN4cat indeed found your branch yesterday.. so this means that you went live with it after all? I'm still stuck with the same thing, planned for upgrade but this migration takes time. I'd like to customize as little as possible from the official master now.

**Comment by daN4cat** [comment]
I was about to go live but I wanted to close 3.2.0 and any bug related to that version before.
Meanwhile I hope to close this cashup as my wife said it will be really handy.
At the moment they are too busy with the new collection coming in to play with any new stuff.

**Comment by daN4cat** [comment]
@odiea I fixed the indexes issue. Thanks for that.

**Comment by odiea** [comment]
Math is correct but there is editing issues.
Start of end of day. Had to close and continue working.
2018-02-21 05_57_13-open source point of sale _ powered by ospos 3 2 0
Back to re enter other items.
2018-02-21 05_57_52-open source point of sale _ powered by ospos 3 2 0

**Comment by daN4cat** [comment]
Ok so it's the logic that is not correct.

**Comment by odiea** [comment]
It appears it does not retain the previous inputed data after an edit. or whatever you said.

**Comment by daN4cat** [comment]
I've done the sum using ajax and using php / cashups controller.
There is no support for special things like adding thousand separator. To be honest I don't know who would like to spend time to do type that...

**Comment by daN4cat** [comment]
@odiea I can still see an issue opening and saving without changing. Numbers are changed... I need to fix that.

**Comment by odiea** [comment]
If you have to make changes that are not in the application folder please let me know. I still have not installed composer or any thing else.

**Comment by daN4cat** [comment]
@odiea I suspect the problem is with old entries. Something is saved in a wrong format.
Try and test with new entries and see if you get the issue.

**Comment by odiea** [comment]
I went and truncated the table. created new cashup and I still have the same issue.

**Comment by daN4cat** [comment]
Can you please check it's not the thousand separator in the form?
Try with something smaller than thousand too.

**Comment by daN4cat** [comment]
because I read 1,000 -> 1 and 2,000 -> 2 in your example. So must be that.

**Comment by daN4cat** [comment]
I thought I could avoid but I need to manage and add new functions to convert format to plain float numbers to avoid the issue.

@jekkos I have a problem with ajax, if I pass a string then on the textinput . val it doesn't accept it. It accepts numbers only.

**Comment by odiea** [comment]
Yes it is a value of 1000 that is creating the issue. Values below that stay just fine. Can you eliminate the thousand separator.

**Comment by daN4cat** [comment]
It's probably better to do the proper job. But tomorrow maybe. I close now.

**Comment by daN4cat** [comment]
OK, one step closer. All the locale, thousand separator included part, is sorted.
I even sorted the ajax issue, I forgot to add the json data type.

Next is the prefilling of the values based on transactions and expenses as previously discussed.

I earlier mentioned to put in grey in the background but probably it's simply better to pre-fill the values so they just need to verify the cash in the till drawer and the card transactions from the Z report and job done. What do you think?

**Comment by odiea** [comment]
Yes. It sounds good to me. Simpler the better for someone that needs to rush home after closing. Does your wife accept checks? It's getting tough here to accept 1.

**Comment by odiea** [comment]
Were You considering creating a Report. If so it would be nice to see the cashup then in details see the expected amounts from the Register. I know. More stuff to do.

**Comment by odiea** [comment]
BTW It works great now.

**Comment by daN4cat** [comment]
We don't accept checks, even a swiped credit card is not recommended. The scam attempts were always with swiped credit cards.

**Comment by daN4cat** [comment]
The problem of pre-filling is... when to do that!
I can assume that if Close cash, close card and close check are 0 we want to pre-fill.

**Comment by odiea** [comment]
The closer should fill out the info and then management will see the expected amount from the Register in the report along with what the closer stated was in it.

**Comment by odiea** [comment]
My lack of trust in people these days.

**Comment by daN4cat** [comment]
I wanted to pre-fill with the values and they just check and submit.

**Comment by odiea** [comment]
You trust people more than I do. That would be fine with me.

**Comment by daN4cat** [comment]
I focus on efficiency

**Comment by odiea** [comment]
25.00  a week may go into an employees pocket. 
52 × weeks in a year.
---------
1,300 = from 1 employee who thinks the owners are rich because they own the business. Just a thought.
If your wife does not have this issue she is 1 lucky person.

**Comment by daN4cat** [comment]
We probably live in a more relaxed way over here in Europe...

**Comment by daN4cat** [comment]
Added the pre-calculations filling in the form.

**Comment by odiea** [comment]
For some reason I m not getting those values changing now.

**Comment by odiea** [comment]
Everything works fine just the way it should. No need to add the ; at line 82. What was going on was I was adding a few original sales. Then I would close. After that the newer sales would not update. It appears that if you update the Cashup before actually closing you will not get the full days totals. Hope you did not waste any time on this.

**Comment by odiea** [comment]
If someone accidentally submits the form before the day close.  Closed cash,cards and checks need to be set to 0. Submit the form. Open the form and the correct totals will show.

**Comment by daN4cat** [comment]
Not sure why my comment was deleted... anyway I fixed a pre-filling issue.

By the way, I'm not totally sure the pre-fill is a good idea in the end.
It should be indeed a report of what is the cash drawer status.... I need to think about it.

**Comment by odiea** [comment]
Sorry I was misunderstanding the logic of prefilling the info. I had no problems once I understood what was happening.

**Comment by odiea** [comment]
I worked on it a little this evening. I added 4 more tables to cashups with the expected prefix. I am using the auto fill to complete the right hand columns. They will be hidden from the normal user unless they have rights to configuration. Let me know what you think about this. I now have to go in and redo the normal cashup code.
2018-03-10 19_43_33-open source point of sale _ powered by ospos 3 2 0

**Comment by daN4cat** [comment]
So the four text boxes on the right are read only and with pre-fill and the ones on the left are for the shop assistant to fill in and close.
Also is the idea to store pre-filled (budget) and actuals in the database as separate?

**Comment by odiea** [comment]
1. Yes and the pre-filled values will only be visible if you have access to the store config. I figured that should only be granted to admins or managers.
2. I added the following to the cashups table. These are what will retain the pre-filled values.
  `expected_closed_amount_cash` decimal(15,2) NOT NULL,
  `expected_closed_amount_card` decimal(15,2) NOT NULL,
  `expected_closed_amount_check` decimal(15,2) NOT NULL,
  `expected_closed_amount_total` decimal(15,2) NOT NULL,

**Comment by odiea** [comment]
We may have to rethink the Cash payments. I just noticed that if someone pays a 1.00 for a .46 cent item the payment is recorded as 1.00. Maybe another column in sales payments for the amount due. A 20.00 dollar payment for a 3 dollar item is going to throw the till off by 17.00 extra. Just hoping this can help your wife's business somehow.

**Comment by odiea** [comment]
This would probably only effect the pre filled values.

**Comment by odiea** [comment]
Ok I got it figured out. I did add another column to sales payments and named it total payments. I did have to add a new summary cashups payments report though.

**Comment by daN4cat** [comment]
I think the cashup as it stands is usable even without the pre-fill.
I've tested a bit and it looks like there are no issue so I'll submit to master and make it part to 3.3.0.

Maybe other people will come up with ideas to improve it, but it's more important to build a end of day report than anything else.

**Pull request closed without merging**
